'use client';

import React, { useState, useRef, useEffect } from 'react';
import { 
  Stack, 
  TextField, 
  Button, 
  Typography
} from '@eventbrite/marmalade';
import { DescriptionSuggestionDialog } from './DescriptionSuggestionDialog';
import styles from './EventSidebar.module.css';

export interface EventData {
  title: string;
  date: string;
  time: string;
  venue: string;
  description: string;
  organizerLogo: string | null;
}

interface EventSidebarProps {
  eventData: EventData;
  onEventDataChange: (data: EventData) => void;
  onDialogStateChange?: (isOpen: boolean) => void;
}

export const EventSidebar: React.FC<EventSidebarProps> = ({
  eventData,
  onEventDataChange,
  onDialogStateChange,
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const uploadButtonRef = useRef<HTMLButtonElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const sidebarRef = useRef<HTMLDivElement>(null);
  
  // Dialog state
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [suggestion, setSuggestion] = useState('');
  const [explanation, setExplanation] = useState('');
  const [isLoadingSuggestion, setIsLoadingSuggestion] = useState(false);
  const [suggestionError, setSuggestionError] = useState<string | null>(null);
  const [pastedText, setPastedText] = useState('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isScanning, setIsScanning] = useState(false);
  const enhancementButtonRef = useRef<HTMLDivElement>(null);

  // Force black circular button styling on upload logo button
  useEffect(() => {
    if (uploadButtonRef.current) {
      const button = uploadButtonRef.current;
      button.style.setProperty('background-color', 'rgba(0, 0, 0, 1)', 'important');
      button.style.setProperty('background', 'rgba(0, 0, 0, 1)', 'important');
      button.style.setProperty('border', 'none', 'important');
      button.style.setProperty('color', 'rgba(255, 255, 255, 1)', 'important');
      button.style.setProperty('border-radius', '50%', 'important');
      button.style.setProperty('width', '40px', 'important');
      button.style.setProperty('height', '40px', 'important');
      button.style.setProperty('min-width', '40px', 'important');
      button.style.setProperty('min-height', '40px', 'important');
      button.style.setProperty('padding', '0', 'important');
      button.style.setProperty('display', 'flex', 'important');
      button.style.setProperty('align-items', 'center', 'important');
      button.style.setProperty('justify-content', 'center', 'important');
      button.style.setProperty('cursor', 'pointer', 'important');
    }
  }, [eventData.organizerLogo]);

  // Auto-resize textarea based on content
  useEffect(() => {
    const textarea = textareaRef.current;
    const sidebar = sidebarRef.current;
    if (!textarea || !sidebar) return;

    // Calculate max height based on available sidebar space
    // Reserve vertical space for enhancement button (50px padding-bottom already in CSS)
    const calculateMaxHeight = () => {
      const sidebarHeight = sidebar.clientHeight;
      const textareaRect = textarea.getBoundingClientRect();
      const sidebarRect = sidebar.getBoundingClientRect();
      const contentTop = textareaRect.top - sidebarRect.top;
      const bottomPadding = 24; // Padding at bottom of sidebar
      const buttonSpace = 50; // Vertical space reserved for enhancement button (matches padding-bottom)
      const availableHeight = sidebarHeight - contentTop - bottomPadding - buttonSpace;
      
      // Ensure minimum height and reasonable max
      return Math.max(80, Math.min(availableHeight - 20, 500));
    };

    const adjustTextareaHeight = () => {
      if (!textarea) return;

      // Reset height to auto to get accurate scrollHeight
      textarea.style.height = 'auto';
      
      // Calculate desired height
      const scrollHeight = textarea.scrollHeight;
      const maxHeight = calculateMaxHeight();
      const newHeight = Math.min(scrollHeight, maxHeight);
      
      // Set the height
      textarea.style.height = `${newHeight}px`;
      
      // Always allow scrolling when content might exceed visible area
      // The padding-right reserves space for the button, so scrollbar won't overlap
      if (scrollHeight > maxHeight) {
        textarea.style.overflowY = 'auto';
      } else {
        // Even if content fits, keep overflow auto to show scrollbar when needed
        // This ensures consistent behavior and prevents button overlap
        textarea.style.overflowY = 'auto';
      }
    };

    // Adjust height when content changes
    adjustTextareaHeight();

    // Also adjust on window resize (in case sidebar height changes)
    window.addEventListener('resize', adjustTextareaHeight);

    return () => {
      window.removeEventListener('resize', adjustTextareaHeight);
    };
  }, [eventData.description]);

  const handleFieldChange = (field: keyof EventData, value: string) => {
    // Allow full text in textarea - don't truncate while typing
    // Truncation only happens when applying/skipping suggestions
    onEventDataChange({
      ...eventData,
      [field]: value,
    });
  };

  // Generate suggestion from API
  const generateSuggestion = async (text: string, showScanning: boolean = true) => {
    console.log('generateSuggestion called with text length:', text.length);
    setIsLoadingSuggestion(true);
    setSuggestionError(null);
    setIsDialogOpen(true); // Show dialog immediately with loading state
    
    if (showScanning) {
      setIsScanning(true);
    }
    
    try {
      console.log('Calling API: /api/description-suggestions');
      // Add timeout to prevent hanging
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout

      const response = await fetch('/api/description-suggestions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ description: text }),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);
      console.log('API response status:', response.status);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMessage = errorData.error || 'Failed to generate suggestion';
        console.error('API error:', errorMessage);
        throw new Error(errorMessage);
      }

      const data = await response.json();
      console.log('API response data:', data);
      
      // Validate response data
      if (!data.suggestion || data.suggestion.trim().length === 0) {
        console.error('Empty suggestion in response');
        throw new Error('Received empty suggestion from server');
      }

      console.log('Setting suggestion:', data.suggestion.substring(0, 50));
      setSuggestion(data.suggestion.trim());
      setExplanation(data.explanation || 'This suggestion focuses on the outcome and value attendees will receive.');
    } catch (error) {
      console.error('Error generating suggestion:', error);
      
      let errorMessage = 'Unable to generate suggestion. Please try again.';
      
      if (error instanceof Error) {
        if (error.name === 'AbortError') {
          errorMessage = 'Request timed out. Please try again.';
        } else if (error.message.includes('Failed to fetch') || error.message.includes('NetworkError')) {
          errorMessage = 'Network error. Please check your connection and try again.';
        } else if (error.message) {
          errorMessage = error.message;
        }
      }
      
      setSuggestionError(errorMessage);
      setIsDialogOpen(true);
    } finally {
      setIsLoadingSuggestion(false);
      setIsScanning(false); // Stop scanning when done
    }
  };

  // Handle paste event
  const handlePaste = async (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
    const pastedText = e.clipboardData.getData('text');
    console.log('Paste detected, text length:', pastedText.length);
    
    // Update the field with full text
    const newDescription = pastedText;
    handleFieldChange('description', newDescription);
    
    // Auto-generate on first time when text exceeds 160 characters
    if (newDescription.length > 160 && !hasAutoGenerated) {
      console.log('Text exceeds 160 chars, auto-generating suggestion');
      setPastedText(newDescription);
      setHasAutoGenerated(true);
      await generateSuggestion(newDescription, true);
    } else {
      console.log('Text is 160 chars or less, or already auto-generated');
    }
  };

  // Handle manual enhancement button click
  const handleEnhancementClick = async () => {
    const currentDescription = eventData.description;
    if (currentDescription.trim().length > 0 && !isLoadingSuggestion) {
      setPastedText(currentDescription);
      await generateSuggestion(currentDescription, true);
    }
  };

  // Handle description change - check for auto-generation on first type
  const handleDescriptionChange = async (value: string) => {
    handleFieldChange('description', value);
    
    // Auto-generate on first time when typing exceeds 160 characters
    // Only trigger if we haven't auto-generated yet and dialog is not already open
    if (value.length > 160 && !hasAutoGenerated && !isDialogOpen && !isLoadingSuggestion) {
      setHasAutoGenerated(true);
      setPastedText(value);
      await generateSuggestion(value, true);
    }
  };

  // Handle Apply action
  const handleApplySuggestion = (editedSuggestion?: string) => {
    const textToApply = editedSuggestion || suggestion;
    if (textToApply) {
      handleFieldChange('description', textToApply);
    }
    setIsDialogOpen(false);
    setSuggestion('');
    setExplanation('');
    setSuggestionError(null);
    setPastedText('');
  };

  // Handle Skip action
  const handleSkipSuggestion = () => {
    // Keep the full original description - don't truncate
    setIsDialogOpen(false);
    setSuggestion('');
    setExplanation('');
    setSuggestionError(null);
    setPastedText('');
    setIsScanning(false);
    // Note: Enhancement button stays visible, hasAutoGenerated stays true
  };

  // Handle dialog close
  const handleCloseDialog = () => {
    // Keep the full original description - don't truncate
    setIsDialogOpen(false);
    setSuggestion('');
    setExplanation('');
    setSuggestionError(null);
    setPastedText('');
    setIsScanning(false);
  };

  // Force black button styling on enhancement button
  useEffect(() => {
    if (enhancementButtonRef.current) {
      const button = enhancementButtonRef.current.querySelector('button');
      if (button) {
        button.style.setProperty('background-color', '#E4E5E6', 'important');
        button.style.setProperty('background', '#E4E5E6', 'important');
        button.style.setProperty('border-color', '#E4E5E6', 'important');
        button.style.setProperty('color', '#000000', 'important');
        button.style.setProperty('opacity', '1', 'important');
        button.style.setProperty('-webkit-text-fill-color', '#000000', 'important');
        
        const allChildren = button.querySelectorAll('*');
        allChildren.forEach((child) => {
          if (child instanceof HTMLElement) {
            child.style.setProperty('color', '#000000', 'important');
            child.style.setProperty('opacity', '1', 'important');
            child.style.setProperty('-webkit-text-fill-color', '#000000', 'important');
          }
        });
      }
    }
  }, [isLoadingSuggestion, eventData.description]);

  // Convert ISO date (YYYY-MM-DD) to mm/dd format for display
  // Preserves partial input (like "1", "12", "12/3") for smooth editing
  const formatDateForInput = (dateString: string): string => {
    if (!dateString) return '';
    
    // If it's already in mm/dd format or partial input (like "1", "12", "12/3"), keep as-is
    // This allows smooth editing without conversion jumps
    if (/^\d{1,2}(\/\d{0,2})?$/.test(dateString)) {
      return dateString;
    }
    
    // Convert from ISO format only if it's a full ISO date (YYYY-MM-DD)
    if (/^\d{4}-\d{2}-\d{2}$/.test(dateString)) {
      try {
        const date = new Date(dateString);
        if (!isNaN(date.getTime())) {
          const month = date.getMonth() + 1;
          const day = date.getDate();
          return `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}`;
        }
      } catch (e) {
        // If parsing fails, return as-is
      }
    }
    
    // For any other format, return as-is
    return dateString;
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const img = new Image();
        img.onload = () => {
          // Create a square canvas for center cropping
          const size = Math.min(img.width, img.height);
          const canvas = document.createElement('canvas');
          canvas.width = size;
          canvas.height = size;
          const ctx = canvas.getContext('2d');
          
          if (ctx) {
            // Calculate the center crop position
            const x = (img.width - size) / 2;
            const y = (img.height - size) / 2;
            
            // Draw the center-cropped image
            ctx.drawImage(img, x, y, size, size, 0, 0, size, size);
            
            // Convert to data URL
            const croppedDataUrl = canvas.toDataURL('image/png');
            
            onEventDataChange({
              ...eventData,
              organizerLogo: croppedDataUrl,
            });
          } else {
            // Fallback to original if canvas context is not available
            onEventDataChange({
              ...eventData,
              organizerLogo: reader.result as string,
            });
          }
        };
        img.onerror = () => {
          // Fallback to original if image load fails
          onEventDataChange({
            ...eventData,
            organizerLogo: reader.result as string,
          });
        };
        img.src = reader.result as string;
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDoneLogo = () => {
    // Remove logo and go back to plus icon state
    onEventDataChange({
      ...eventData,
      organizerLogo: null,
    });
  };

  const handleLogoClick = () => {
    fileInputRef.current?.click();
  };

  const handleRemoveLogo = () => {
    onEventDataChange({
      ...eventData,
      organizerLogo: null,
    });
  };

  return (
    <div ref={sidebarRef} className={styles.sidebar}>
      <div className={styles.content}>
        <Typography variant="heading-md" className={styles.heading}>Create your event discovery card</Typography>
        <Stack space="spacing-md">
          <Stack space="spacing-lg">
          <div className={styles.textFieldWrapper}>
            <TextField
              label="Event Title"
              placeholder="Enter event title"
              value={eventData.title}
              onChange={(value) => handleFieldChange('title', value)}
            />
          </div>

          <div className={styles.dateTimeRow}>
            <div className={styles.inputWrapper}>
              <label className={styles.label}>Date</label>
              <input
                type="text"
                className={styles.input}
                placeholder="mm/dd"
                value={formatDateForInput(eventData.date)}
                onChange={(e) => {
                  const value = e.target.value;
                  // Allow only digits and forward slash
                  let cleaned = value.replace(/[^\d/]/g, '');
                  
                  // Smart formatting: only add slash when user types naturally
                  // Don't force formatting if user is still typing
                  if (cleaned.length > 0 && !cleaned.includes('/')) {
                    // If user types 2+ digits without slash, add slash after 2nd digit
                    if (cleaned.length >= 2) {
                      cleaned = cleaned.slice(0, 2) + '/' + cleaned.slice(2);
                    }
                  }
                  
                  // Limit to 5 characters (mm/dd)
                  cleaned = cleaned.slice(0, 5);
                  
                  // Store as mm/dd format while typing (smooth editing)
                  handleFieldChange('date', cleaned);
                }}
                onFocus={(e) => {
                  // When focusing, if it's an ISO date, convert to mm/dd for editing
                  const value = e.target.value;
                  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
                    try {
                      const date = new Date(value);
                      if (!isNaN(date.getTime())) {
                        const month = date.getMonth() + 1;
                        const day = date.getDate();
                        const formatted = `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}`;
                        handleFieldChange('date', formatted);
                      }
                    } catch (e) {
                      // Keep as-is if conversion fails
                    }
                  }
                }}
                onBlur={(e) => {
                  // Validate and normalize date format on blur
                  const value = e.target.value.trim();
                  
                  if (value.length === 0) {
                    handleFieldChange('date', '');
                    return;
                  }
                  
                  const parts = value.split('/');
                  if (parts.length === 2) {
                    const month = parseInt(parts[0], 10);
                    const day = parseInt(parts[1], 10);
                    
                    // Validate month and day ranges
                    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
                      // Convert to ISO format for storage (using current year)
                      const currentYear = new Date().getFullYear();
                      const date = new Date(currentYear, month - 1, day);
                      
                      // Validate the date is valid (handles invalid dates like Feb 30)
                      if (date.getMonth() === month - 1 && date.getDate() === day) {
                        const isoDate = date.toISOString().split('T')[0];
                        handleFieldChange('date', isoDate);
                      } else {
                        // Invalid date (e.g., Feb 30), keep as mm/dd format
                        const normalized = `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}`;
                        handleFieldChange('date', normalized);
                      }
                    } else {
                      // Invalid month or day, keep as-is
                      handleFieldChange('date', value);
                    }
                  } else {
                    // Invalid format, keep as-is
                    handleFieldChange('date', value);
                  }
                }}
              />
            </div>
            <div className={styles.inputWrapper}>
              <label className={styles.label}>Time</label>
              <input
                type="time"
                className={styles.input}
                value={eventData.time}
                onChange={(e) => handleFieldChange('time', e.target.value)}
              />
            </div>
          </div>

          <div className={styles.textFieldWrapper}>
            <TextField
              label="Venue"
              placeholder="Enter venue name"
              value={eventData.venue}
              onChange={(value) => handleFieldChange('venue', value)}
            />
          </div>

          <div className={styles.textAreaWrapper}>
            <div className={styles.labelRow}>
              <label className={styles.label}>
                Description
              </label>
              <span className={styles.charCount}>
                {eventData.description.length}/160
                {eventData.description.length > 160 && (
                  <span style={{ color: 'var(--color-danger, #dc2626)', marginLeft: '4px' }}>
                    (will be truncated)
                  </span>
                )}
              </span>
            </div>
            <span className={styles.helperText}>
              Outcome-driven summary to help attendees imagine what they will get from your event.
            </span>
            <div className={styles.textAreaContainer}>
              <textarea
                ref={textareaRef}
                className={`${styles.textArea} ${isScanning ? styles.scanning : ''}`}
                placeholder="Describe your event..."
                value={eventData.description}
                onChange={(e) => handleDescriptionChange(e.target.value)}
                onPaste={handlePaste}
              />
              {eventData.description.length > 0 && (
                <div ref={enhancementButtonRef} className={styles.enhancementButtonWrapper}>
                  <Button
                    variant="secondary"
                    onClick={handleEnhancementClick}
                    disabled={isLoadingSuggestion || !eventData.description.trim()}
                    className={styles.enhancementButton}
                  >
                    {isLoadingSuggestion ? 'Enhancing...' : 'Enhance'}
                  </Button>
                </div>
              )}
            </div>
          </div>

          <div className={styles.logoSection}>
            <Typography variant="body-sm-bold">Organizer Logo</Typography>
            <span className={styles.helperText}>
              Upload your logo helps build trust and allow attendees to discover your organization.
            </span>
            
            {eventData.organizerLogo ? (
              <div className={styles.logoPreview}>
                <img 
                  src={eventData.organizerLogo} 
                  alt="Organizer logo" 
                  className={styles.logoImage}
                />
                <div className={styles.logoActions}>
                  <Button 
                    variant="primary"
                    onClick={handleDoneLogo}
                  >
                    Done
                  </Button>
                  <Button 
                    variant="secondary"
                    onClick={handleRemoveLogo}
                    className={styles.removeButton}
                  >
                    Remove
                  </Button>
                </div>
              </div>
            ) : (
              <div className={styles.logoUpload}>
                <button
                  ref={uploadButtonRef}
                  onClick={handleLogoClick}
                  aria-label="Upload logo"
                  type="button"
                  className={styles.uploadLogoButton}
                >
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className={styles.plusIcon}
                  >
                    <path
                      d="M12 5V19M5 12H19"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </button>
              </div>
            )}
            
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              onChange={handleLogoUpload}
              className={styles.hiddenInput}
            />
          </div>
        </Stack>
        </Stack>
      </div>

      {/* Description Suggestion Dialog */}
      <DescriptionSuggestionDialog
        isOpen={isDialogOpen}
        originalText={pastedText || eventData.description}
        suggestion={suggestion}
        explanation={explanation}
        isLoading={isLoadingSuggestion}
        error={suggestionError}
        onApply={handleApplySuggestion}
        onSkip={handleSkipSuggestion}
        onClose={handleCloseDialog}
        onDialogStateChange={onDialogStateChange}
      />
    </div>
  );
};

